# This script configures the build on continuous integration for Windows

# Set the image to be used
image:
  - Visual Studio 2015

# Set environment to the required version of node
environment:
  matrix:
    - NODE_AND_NPM_VERSIONS: "10:5.7.1"
    - NODE_AND_NPM_VERSIONS: "12:6.14.4"
  DETECT_CHROMEDRIVER_VERSION: true

branches:
  only:
    - master
    - develop
    - v2-master
    - v2-develop

# Install Scripts
install:
  # Update pre-installed Chrome to latest
  - ps: |
      $env:CHROME_INSTALLER = "chrome_installer.exe";
      Invoke-WebRequest "http://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile ($env:TEMP + "\" + $env:CHROME_INSTALLER);
      Start-Process -FilePath ($env:TEMP + "\" + $env:CHROME_INSTALLER) -ArgumentList "/silent /install" -Verb RunAs -Wait;
      Remove-Item ($env:TEMP + "\" + $env:CHROME_INSTALLER);

  # Get node version as listed in the environment
  - ps: |
      $node_version = $env:NODE_AND_NPM_VERSIONS.Split(":")[0]
      Install-Product node $node_version x64

  # Install npm
  - ps: |
      $npm_package = "npm@" + $env:NODE_AND_NPM_VERSIONS.Split(":")[1]
      npm install -g $npm_package

  # Install the node dependencies
  - npm ci

# Disable automatic build phase
build: off

test_script:
  # Print the version of node and npm that we are working with
  - node --version
  - npm --version

  # Run fast unit tests
  - npm run test

  # Run e2e tests on nightly builds only
  - if "%APPVEYOR_SCHEDULED_BUILD%" == "True" (npm run test:e2e-ci)

  # Run the slow integration tests and end-to-end tests if the branch
  # being merged to is the master branch
  - if %APPVEYOR_REPO_BRANCH% == master (npm run test:integration)
  - if %APPVEYOR_REPO_BRANCH% == v2-master (npm run test:integration)
