# This is a config for verdaccio, a private NPM repository you can run yourself.
# The repository is unsecured and only intended to be run locally - don't expose
# it on the internet.

storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    max_fails: 100
    cache: true

# Allow anybody to publish any package, with no auth.
packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    access: $all
    publish: $all
    proxy: npmjs

publish:
  allow_offline: true

logs:
  - {type: file, path: ./verdaccio.log, level: debug}
